import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  const workspace = await prisma.workspace.upsert({
    where: { slug: 'seed-workspace' },
    update: {},
    create: { id: 'seed-workspace', name: 'Seed Workspace', slug: 'seed-workspace' },
  });
  // Create project
  const project = await prisma.project.upsert({
    where: { id: 'servios-cms' },
    update: {},
    create: {
      id: 'servios-cms',
      name: 'Servios CMS',
      description: 'Test case untuk CMS Servios - Sistem manajemen restoran',
      workspaceId: workspace.id,
    },
  });

  // Create modules
  const cmsLogin = await prisma.module.upsert({ where: { id: 'mod-cms-login' }, update: {}, create: { id: 'mod-cms-login', name: 'CMS Login', projectId: project.id } });
  const dashboard = await prisma.module.upsert({ where: { id: 'mod-dashboard' }, update: {}, create: { id: 'mod-dashboard', name: 'Dashboard', projectId: project.id } });
  const orderMgmt = await prisma.module.upsert({ where: { id: 'mod-order-mgmt' }, update: {}, create: { id: 'mod-order-mgmt', name: 'Order Management', projectId: project.id } });
  const productMgmt = await prisma.module.upsert({ where: { id: 'mod-product-mgmt' }, update: {}, create: { id: 'mod-product-mgmt', name: 'Product Management', projectId: project.id } });
  const paymentMgmt = await prisma.module.upsert({ where: { id: 'mod-payment-mgmt' }, update: {}, create: { id: 'mod-payment-mgmt', name: 'Payment Management', projectId: project.id } });

  // Create test cases
  const testCases = [
    { testCaseId: 'A-001', page: 'CMS Login', subMenu: null, weight: '16.60%', testType: 'Positive', testAction: 'Login dengan akun yang sudah ada', steps: '- Buka website CMS\n- Masukan Email\n- Masukan Password\n- tekan tombol login atau enter', expectedResult: 'Berhasil Login', actualResult: 'Berhasil Login', status: 'DONE', progress: 100, remarks: '14 agustus 2025 = SUKSES', priority: 'High', moduleId: cmsLogin.id },
    { testCaseId: 'A-001', page: 'CMS Login', subMenu: null, weight: '16.60%', testType: 'Negative', testAction: 'Login dengan password disengajakan salah', steps: '- Buka website CMS\n- Masukan Email\n- Masukan Password salah\n- tekan tombol login atau enter', expectedResult: 'Gagal login', actualResult: 'Gagal login', status: 'DONE', progress: 100, remarks: '14 agustus 2025 = SUKSES', priority: 'High', moduleId: cmsLogin.id },
    { testCaseId: 'A-001', page: 'CMS Login', subMenu: null, weight: '16.60%', testType: 'Negative', testAction: 'Login dengan email disengajakan salah', steps: '- Buka website CMS\n- Masukan Email salah\n- Masukan Password\n- tekan tombol login atau enter', expectedResult: 'Gagal login', actualResult: 'Gagal login', status: 'DONE', progress: 100, remarks: '14 agustus 2025 = SUKSES', priority: 'High', moduleId: cmsLogin.id },
    { testCaseId: 'A-001', page: 'CMS Login', subMenu: null, weight: '16.60%', testType: 'Negative', testAction: 'Login dengan akun yang belum ada', steps: '- Buka website CMS\n- Masukan Email belum terdaftar\n- Masukan Password\n- tekan tombol login atau enter', expectedResult: 'Gagal login', actualResult: 'Gagal login', status: 'DONE', progress: 100, remarks: '14 agustus 2025 = SUKSES', priority: 'High', moduleId: cmsLogin.id },
    { testCaseId: 'A-001', page: 'CMS Login', subMenu: null, weight: '16.60%', testType: 'Negative', testAction: 'Login dengan email dan password kosong', steps: '- Buka website CMS\n- tekan tombol login atau enter', expectedResult: 'Error handler untuk mengisi field email dan password', actualResult: 'Error handler untuk mengisi field email dan password', status: 'DONE', progress: 100, remarks: '14 agustus 2025 = SUKSES', priority: 'High', moduleId: cmsLogin.id },
    { testCaseId: 'A-001', page: 'CMS Login', subMenu: null, weight: '16.60%', testType: 'Positive', testAction: 'Login dengan user admin privilege berbeda (non admin)', steps: '- Buka website CMS\n- Masukan Email\n- Masukan Password\n- tekan tombol login atau enter', expectedResult: 'Berhasil Login', actualResult: 'Berhasil Login', status: 'DONE', progress: 100, remarks: '20 agustus 2025 = SUKSES', priority: 'Medium', moduleId: cmsLogin.id },
    { testCaseId: 'A-002', page: 'Dashboard', subMenu: null, weight: null, testType: 'Positive', testAction: 'Menampilkan dashboard', steps: '- Login ke CMS\n- Buka halaman dashboard', expectedResult: 'Dashboard tampil dengan data yang sesuai', actualResult: null, status: 'NOT DONE', progress: 0, remarks: null, priority: 'Medium', moduleId: dashboard.id },
    { testCaseId: 'A-003', page: 'CMS Order Management', subMenu: 'Order List', weight: '6.25%', testType: 'Positive', testAction: 'Membuat order baru (Dine in, Pickup at counter)', steps: '- Login ke CMS\n- Pada Order Management pilih Order list\n- Pilih New\n- Pilih order type lalu pilih dine in\n- Pilih food method lalu pilih pick up at counter\n- Pilih payment type\n- Pilih add product\n- Pilih product dari dropdown\n- Submit', expectedResult: 'Order berhasil tersimpan di order list', actualResult: 'Order berhasil tersimpan di order list', status: 'DONE', progress: 100, remarks: '27 agustus 2025 = SUKSES', priority: 'High', moduleId: orderMgmt.id },
    { testCaseId: 'A-003', page: 'CMS Order Management', subMenu: 'Order List', weight: '6.25%', testType: 'Positive', testAction: 'Membuat order baru Delivery (Dine in, Table delivery)', steps: '- Login ke CMS\n- Pada Order Management pilih Order list\n- Pilih New\n- Pilih order type lalu pilih dine in\n- Pilih food method lalu pilih table delivery\n- Isi table number\n- Pilih add product\n- Pilih product dari dropdown\n- Submit', expectedResult: 'Field number table harus terisi dan order berhasil', actualResult: 'Field number table harus terisi dan order berhasil', status: 'DONE', progress: 100, remarks: '27 agustus 2025 = SUKSES', priority: 'High', moduleId: orderMgmt.id },
    { testCaseId: 'A-003', page: 'CMS Order Management', subMenu: 'Order List', weight: '6.25%', testType: 'Positive', testAction: 'Membuat order baru (Takeaway)', steps: '- Login ke CMS\n- Pada Order Management pilih Order list\n- Pilih New\n- Pilih order type lalu pilih Takeaway\n- Pilih food method\n- Pilih add product\n- Submit', expectedResult: 'Field food method dan order type sudah terisi dan order berhasil', actualResult: 'Field food method dan order type sudah terisi dan order berhasil', status: 'DONE', progress: 100, remarks: '27 agustus 2025 = SUKSES', priority: 'High', moduleId: orderMgmt.id },
    { testCaseId: 'A-003', page: 'CMS Order Management', subMenu: 'Order List', weight: '6.25%', testType: 'Negative', testAction: 'Submit order tanpa product', steps: '- Login ke CMS\n- Pada Order Management pilih Order list\n- Pilih New\n- Pilih order type\n- Pilih food method\n- Pilih payment type\n- Submit tanpa add product', expectedResult: 'Error handler product tidak boleh kosong', actualResult: 'Error handler product tidak boleh kosong', status: 'DONE', progress: 100, remarks: '28 agustus 2025 = SUKSES', priority: 'High', moduleId: orderMgmt.id },
    { testCaseId: 'A-003', page: 'CMS Order Management', subMenu: 'Order List', weight: '6.25%', testType: 'Negative', testAction: 'Submit dine in table delivery tanpa mengisi table number', steps: '- Login ke CMS\n- Pada Order Management pilih Order list\n- Pilih New\n- Pilih order type dine in\n- Pilih food method table delivery\n- Tidak isi table number\n- Submit', expectedResult: 'Error harus mengisi table number', actualResult: 'Error harus mengisi table number', status: 'DONE', progress: 100, remarks: '27 agustus 2025 = SUKSES', priority: 'High', moduleId: orderMgmt.id },
    { testCaseId: 'A-003', page: 'CMS Order Management', subMenu: 'Order List', weight: '6.25%', testType: 'Negative', testAction: 'Mengisi quantity produk dibawah 1', steps: '- Login ke CMS\n- Pada Order Management pilih Order list\n- Pilih New\n- Add product\n- Kurangi quantity product menjadi 0', expectedResult: 'Error minimal quantity 1', actualResult: 'Error minimal quantity 1', status: 'DONE', progress: 100, remarks: '28 agustus 2025 = SUKSES', priority: 'Medium', moduleId: orderMgmt.id },
    { testCaseId: 'A-004', page: 'CMS Product Management', subMenu: 'Product', weight: '2%', testType: 'Positive', testAction: 'Membuat product baru', steps: '- Login ke CMS\n- Pada Product Management pilih Product\n- Pilih New\n- Masuk ke tab general\n- Masukan nama, kategori, tag, harga, stock, description\n- Submit', expectedResult: 'Product berhasil dibuat dan muncul di list product', actualResult: 'Product berhasil dibuat dan muncul di list product', status: 'DONE', progress: 100, remarks: '20 agustus 2025 = SUKSES', priority: 'High', moduleId: productMgmt.id },
    { testCaseId: 'A-004', page: 'CMS Product Management', subMenu: 'Product', weight: '2%', testType: 'Positive', testAction: 'Melihat detail product yang sudah dibuat', steps: '- Login ke CMS\n- Pada Product Management pilih Product\n- Pilih View (logo mata)\n- Cek tab general dan customize', expectedResult: 'Detail product berhasil dilihat', actualResult: 'Detail product berhasil dilihat', status: 'DONE', progress: 100, remarks: '20 agustus 2025 = SUKSES', priority: 'Medium', moduleId: productMgmt.id },
    { testCaseId: 'A-004', page: 'CMS Product Management', subMenu: 'Product', weight: '2%', testType: 'Positive', testAction: 'Mengedit product yang sudah dibuat', steps: '- Login ke CMS\n- Pada Product Management pilih Product\n- Pilih Edit (Logo pensil)\n- Ubah field yang diinginkan\n- Submit', expectedResult: 'Product berhasil diedit', actualResult: 'Product berhasil diedit', status: 'DONE', progress: 100, remarks: '20 agustus 2025 = SUKSES', priority: 'Medium', moduleId: productMgmt.id },
    { testCaseId: 'A-004', page: 'CMS Product Management', subMenu: 'Product', weight: '2%', testType: 'Positive', testAction: 'Menghapus product yang sudah dibuat', steps: '- Login ke CMS\n- Pada Product Management pilih Product\n- Pilih Delete (logo trashcan)\n- Muncul konfirmasi delete, pilih "yes, delete"', expectedResult: 'Product berhasil dihapus', actualResult: 'Product berhasil dihapus', status: 'DONE', progress: 100, remarks: '20 agustus 2025 = SUKSES', priority: 'Medium', moduleId: productMgmt.id },
    { testCaseId: 'A-004', page: 'CMS Product Management', subMenu: 'Product', weight: '2%', testType: 'Negative', testAction: 'Tidak mengisi field yang wajib diisi', steps: '- Login ke CMS\n- Pada Product Management pilih Product\n- Pilih New\n- Tidak isi field wajib\n- Submit', expectedResult: 'Error handler field wajib diisi', actualResult: 'Error handler field wajib diisi', status: 'DONE', progress: 100, remarks: '20 agustus 2025 = SUKSES', priority: 'Medium', moduleId: productMgmt.id },
    { testCaseId: 'A-004', page: 'CMS Product Management', subMenu: 'Category Product', weight: '2%', testType: 'Positive', testAction: 'Membuat kategori product baru', steps: '- Login ke CMS\n- Pada Product Management pilih Category\n- Pilih Category Product\n- Pilih New\n- Masukan nama, sequence, dan foto kategori\n- Submit', expectedResult: 'Kategori product berhasil dibuat dan muncul di list', actualResult: 'Kategori product berhasil dibuat dan muncul di list', status: 'DONE', progress: 100, remarks: '25 agustus 2025 = SUKSES', priority: 'Medium', moduleId: productMgmt.id },
    { testCaseId: 'A-004', page: 'CMS Product Management', subMenu: 'Tag', weight: '2%', testType: 'Positive', testAction: 'Membuat tag baru', steps: '- Login ke CMS\n- Pada Product Management pilih Tag\n- Pilih New\n- Isi nama tag\n- Centang IsActivated\n- Submit', expectedResult: 'Tag berhasil dibuat dan muncul di list tag', actualResult: 'Tag berhasil dibuat dan muncul di list tag', status: 'DONE', progress: 100, remarks: '20 agustus 2025 = SUKSES', priority: 'Low', moduleId: productMgmt.id },
    { testCaseId: 'A-004', page: 'CMS Product Management', subMenu: 'Ingredient', weight: '2%', testType: 'Positive', testAction: 'Membuat ingredient baru', steps: '- Login ke CMS\n- Pada Product Management pilih Ingredient\n- Pilih New\n- Isi nama ingredient\n- Centang IsActivated\n- Submit', expectedResult: 'Ingredient berhasil dibuat dan muncul di list', actualResult: 'Ingredient berhasil dibuat dan muncul di list', status: 'DONE', progress: 100, remarks: '27 agustus 2025 = SUKSES', priority: 'Low', moduleId: productMgmt.id },
    { testCaseId: 'A-004', page: 'CMS Product Management', subMenu: 'Topping', weight: '2%', testType: 'Positive', testAction: 'Membuat topping baru', steps: '- Login ke CMS\n- Pada Product Management pilih Topping\n- Pilih New\n- Isi nama Topping\n- Centang IsActivated\n- Submit', expectedResult: 'Topping berhasil dibuat dan muncul di list', actualResult: 'Topping berhasil dibuat dan muncul di list', status: 'DONE', progress: 100, remarks: '27 agustus 2025 = SUKSES', priority: 'Low', moduleId: productMgmt.id },
    { testCaseId: 'A-004', page: 'CMS Product Management', subMenu: 'Combo', weight: '2%', testType: 'Positive', testAction: 'Membuat combo baru', steps: '- Login ke CMS\n- Pada Product Management pilih Combo\n- Pilih New\n- Isi nama, harga, description, foto combo, dan Product\n- Centang IsActivated\n- Submit', expectedResult: 'Combo berhasil dibuat dan muncul di list combo', actualResult: 'Combo berhasil dibuat dan muncul di list combo', status: 'DONE', progress: 100, remarks: '20 agustus 2025 = SUKSES', priority: 'Low', moduleId: productMgmt.id },
    { testCaseId: 'A-004', page: 'CMS Product Management', subMenu: 'Combo', weight: '2%', testType: 'Negative', testAction: 'Membuat combo dengan nama yang sudah ada', steps: '- Login ke CMS\n- Pada Product Management pilih Combo\n- Pilih New\n- Isi nama combo dengan nama yang sudah terdaftar\n- Submit', expectedResult: 'Error handler nama sudah ada', actualResult: 'Error handler nama sudah ada', status: 'DONE', progress: 100, remarks: '9 september 2025 = SUKSES', priority: 'Medium', moduleId: productMgmt.id },
    { testCaseId: 'A-004', page: 'CMS Product Management', subMenu: 'Product', weight: '2%', testType: 'Positive', testAction: 'Memastikan Ingredient mandatory di menu customize', steps: '- Login ke CMS\n- Pada Product Management pilih Product\n- Pilih Edit\n- Pada customize section, add ingredient\n- Set IsDefault ke Yes\n- Save', expectedResult: 'Ingredient mandatory harus diisi minimal 1 ingredient', actualResult: null, status: 'NOT DONE', progress: 0, remarks: null, priority: 'High', moduleId: productMgmt.id },
    { testCaseId: 'A-005', page: 'CMS Order Management', subMenu: 'Payment List', weight: '11.11%', testType: 'Positive', testAction: 'Check order yang sudah membuat payment dari payment list', steps: '- Login ke CMS\n- Pada Order Management pilih Payment details\n- Pilih Payment list', expectedResult: 'Order yang sudah membuat payment muncul di list', actualResult: 'Order yang sudah membuat payment muncul di list', status: 'DONE', progress: 100, remarks: '25 agustus 2025 = SUKSES', priority: 'High', moduleId: paymentMgmt.id },
    { testCaseId: 'A-005', page: 'CMS Order Management', subMenu: 'Payment List', weight: '11.11%', testType: 'Positive', testAction: 'Cash payment dengan uang pas', steps: '- Login ke CMS\n- Pada Order Management pilih Payment details\n- Klik search order\n- Lihat detail order dan total harga\n- Isi jumlah uang sesuai dengan harga total\n- Klik Process order', expectedResult: 'Payment berhasil dengan status = cukup, sisa "0" listed', actualResult: 'Payment berhasil dengan status = cukup, sisa "0" listed', status: 'DONE', progress: 100, remarks: '25 agustus 2025 = SUKSES', priority: 'High', moduleId: paymentMgmt.id },
    { testCaseId: 'A-005', page: 'CMS Order Management', subMenu: 'Payment List', weight: '11.11%', testType: 'Positive', testAction: 'Cash payment dengan uang lebih', steps: '- Login ke CMS\n- Pada Order Management pilih Payment details\n- Klik search order\n- Isi jumlah uang lebih dari harga total\n- Klik Process order', expectedResult: 'Payment berhasil dengan status = cukup, sisa total kembalian', actualResult: 'Payment berhasil dengan status = cukup, sisa total kembalian', status: 'DONE', progress: 100, remarks: '25 agustus 2025 = SUKSES', priority: 'High', moduleId: paymentMgmt.id },
    { testCaseId: 'A-003', page: 'CMS Order Management', subMenu: 'Order Type', weight: null, testType: 'Positive', testAction: 'Menampilkan order type', steps: '- Login ke CMS\n- Pada Order Management pilih Order Type', expectedResult: 'Daftar order type tampil', actualResult: null, status: 'NOT DONE', progress: 0, remarks: null, priority: 'Medium', moduleId: orderMgmt.id },
    { testCaseId: 'A-003', page: 'CMS Order Management', subMenu: 'Food Method', weight: null, testType: 'Positive', testAction: 'Menampilkan food method', steps: '- Login ke CMS\n- Pada Order Management pilih Food Method', expectedResult: 'Daftar food method tampil', actualResult: null, status: 'NOT DONE', progress: 0, remarks: null, priority: 'Medium', moduleId: orderMgmt.id },
    { testCaseId: 'A-005', page: 'CMS Order Management', subMenu: 'Payment Type', weight: null, testType: 'Positive', testAction: 'Menampilkan payment type', steps: '- Login ke CMS\n- Pada Order Management pilih Payment Type', expectedResult: 'Daftar payment type tampil', actualResult: null, status: 'NOT DONE', progress: 0, remarks: null, priority: 'Medium', moduleId: paymentMgmt.id },
    { testCaseId: 'A-005', page: 'CMS Order Management', subMenu: 'Payment Group', weight: null, testType: 'Positive', testAction: 'Menampilkan payment group', steps: '- Login ke CMS\n- Pada Order Management pilih Payment Group', expectedResult: 'Daftar payment group tampil', actualResult: null, status: 'NOT DONE', progress: 0, remarks: null, priority: 'Medium', moduleId: paymentMgmt.id },
    { testCaseId: 'A-005', page: 'CMS Order Management', subMenu: 'Payment Methods', weight: null, testType: 'Positive', testAction: 'Menampilkan payment methods', steps: '- Login ke CMS\n- Pada Order Management pilih Payment Methods', expectedResult: 'Daftar payment methods tampil', actualResult: null, status: 'NOT DONE', progress: 0, remarks: null, priority: 'Medium', moduleId: paymentMgmt.id },
  ];

  for (const tc of testCases) {
    await prisma.testCase.create({
      data: {
        testCaseId: tc.testCaseId,
        page: tc.page,
        subMenu: tc.subMenu,
        weight: tc.weight,
        testType: tc.testType,
        testAction: tc.testAction,
        steps: tc.steps,
        expectedResult: tc.expectedResult,
        actualResult: tc.actualResult,
        status: tc.status,
        progress: tc.progress,
        remarks: tc.remarks,
        priority: tc.priority,
        projectId: project.id,
        moduleId: tc.moduleId,
      },
    });
  }

  console.log('Seed completed!');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
